build.version=1.0
cards.message=Welcome to EzBank account related local APIs
cards.contactDetails.name=Sheryash Kakde - prod-sk Lead CARDS-MS
cards.contactDetails.email="{cypher}c5a88fbf06d6f714a98c863ebadda1ef137fdf1ec9b24f42bff147618dbda6ffe4d206340c9ba4565ff3d50f52c9c612"
cards.onCallSupport=9999999999
